### ISSUE TITLE
Should naming of object attributes, e.g. `sd_vvp_thresh`, made consistent with new function names?

### ISSUE THREAD

**Issue by stijnvanhoey** [adokter/bioRad#107]
With regard to the method sd_vvp, the threshold retrieved is from: `x$attributes$how$sd_vvp_thresh` (for the get and set). Do we want to change the structure itself as well to `x$attributes$how$rvsd_thresh`, @adokter ?

For the moment, this brings a bit of confusion in the documentation description: e.g. Sets the threshold in \code{sd_vvp}. If we keep the data structure as such, do we use that naming in the description or call it `rvsd` here as well?

**Comment by adokter** [comment]
The problem is that sd_vvp is a column hard-coded in the C-code of the algorithm, and that name has already been fixed. In that sense we cannot get rid of sd_vvp, unless I change the C-code and the hdf5 data model, which won't be good for backward compatibility. The inconsistency makes me wonder whether we wouldn't be better with sticking to sd_vvp() instead of rvsd() after all. Another inconsistency is that rv stands for radial velocity, but as a quantity in the package radial velocity is called VRADH (or sometimes VRAD) ..

The `x$attributes$how$sd_vvp_thresh` is also hard coded in C output of the algorithm, so we cannot change it.

**Comment by peterdesmet** [comment]
Yeah, also wondered by renaming it back. “rvsd” only seems to add to the confusion. Who will tackle this?

**Comment by adokter** [comment]
I renamed `sd_vvp` to `sd_vvp_threshold` in order to be able to distinguish the profile quantity `sd_vvp` from the threshold against which this quantity is compared.

**Comment by stijnvanhoey** [comment]
Just to check: in the function `calculate_vp`,  `sd_vpp` is an input parameter to the function, ok?

**Comment by stijnvanhoey** [comment]
Related to the first question: The attribute  naming of the output from `integrate_profile` is currently `attributes(output)$alt.min <- alt.min`, see https://github.com/adokter/bioRad/blob/develop/R/integrate_profile.R#L161 I do think we can use 
`attributes(output)$alt_min <- alt_min` here for the attribute?

**Comment by adokter** [comment]
Regarding https://github.com/adokter/bioRad/issues/107#issuecomment-409608834, yes we can use `attributes(output)$alt_min <- alt_min`

**Comment by adokter** [comment]
Regarding https://github.com/adokter/bioRad/issues/107#issuecomment-409608001, `sd_vvp_threshold` is now the input parameter to the function. `sd_vvp` is a quantity in the profile, i.e. it has a value for each altitude bin.

**Comment by stijnvanhoey** [comment]
Ok, so we have to adapt the [overview of argument adaptations #112](https://github.com/adokter/bioRad/issues/112#issuecomment-394833402) `calculate_vp` as there the `sd_vvp` is still provided as an argument...

**Comment by stijnvanhoey** [comment]
See commit https://github.com/adokter/bioRad/commit/94ec7be67d45b0b5b936d24921d2a5b03842a8b4 for the reset to `sd_vvp_threshold`
