### ISSUE TITLE
Add sections back to reference list

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#110]
The [reference list](https://rawgit.com/adokter/bioRad/c17d0e51103d67131385b0018687276a2cd9becf/docs/reference/index.html) is currently automatic generated, to more easily check if functions get added correctly. Should be divided up in sections again:

1. Solve #109 first
2. Use [the old sectioned reference list](https://github.com/adokter/bioRad/blob/841c39ff9e6880f63d9799451e96d3a7c2d4659f/_pkgdown.yml) as inspiration to divide in sections.
3. Don't forget to add [deprecated functions page](https://rawgit.com/adokter/bioRad/c17d0e51103d67131385b0018687276a2cd9becf/docs/reference/bioRad-deprecated.html)

**Comment by peterdesmet** [comment]
@adokter when are you planning to merge `develop` into `master`? I'd rather wait for that before adding the sections back to the reference list (if still needed).

**Comment by adokter** [comment]
Yes good idea for this manual page to be finished before we merge to master

**Comment by peterdesmet** [comment]
Here's my proposal for organizing the bioRad functions on the website. @adokter @stijnvanhoey @plieper @CeciliaNilsson709 feedback welcome! 

- I aimed to have a limited number of sections (see sidebar), in an intuitive order, with the functions in a intuitive order as well. Since we have to list all functions, that's not always easy, but let me know if some look out of place to you.
- Each section has a short description: useful to explain what e.g. "integrate" is about
- `nexrad_to_odim` is listed under 2 sections: maybe it should only be listed under 
"Creating" as it requires docker
- Wasn't entirely sure where to list the `sd_vvp_threshold` and `rcs` functions (now under vpts)

![function reference biorad](https://user-images.githubusercontent.com/600993/45500524-1f614c80-b77f-11e8-9546-d5f48306fbe5.png)

**Comment by plieper** [comment]
Hi Peter,

It looks good and intuitive. A couple of comments:

**Reading radar data**
- difference between `is.pvolfile()` and `is.pvol()` I didn't find immediately clear. Apparently you use `is.pvolfile()` when you want to check a file on your computer that you didn't yet read in, and use `is.pvol()` for a file you already did read in (yeah, both are 'files' for me). Adding "Check if a *local* file is a polar volume (`pvol`)" would make it more clear for my, but maybe that's personal :-).
- I'm inclined to keep `nexrad_to_odim` here, as it fits in the topic about polar volumes.
- `summary(<pvol>)` is the same as just tying `<pvol>`. Not clear why you want to type extra to get the same result :-). But maybe that's more a question for @adokter ?
- the descriptions of `summary(<pvol>)`, `is.pvol()` I don't find very informative, because these functions do more than telling you the class of the object. Lower in the list you describe `is.vpfile()`, so I'd do the same here for `is.pvol()` and add a description for `summary(<pvol>)`.

**Inspecting a radar scan**
- same comment for `summary(<scan>)`, `is.scan()` etc.

**Projecting a radar scan**
- same comment for `summary(<ppi>)`, `is.ppi()` etc.

**Creating vertical profiles of birds**
- I'd put  `check_docker()` before `update_docker()`, because before I'd update Docker, I'd first check it. Again, this may be personal :-).

**Combining vertical profiles into time series**
- I'd leave `sd_vvp_threshold()` and `rcs` here, as you use them with vp's and vpts'.

**Comment by CeciliaNilsson709** [comment]
Agree that it looks great 👏👏. Some small comments from my (naive) point of view:

I also agree with Liesbeth that the description on the `summary(<pvol>)`, `is.pvol()` etc is not that intuitive, and my personal preference would be to have each function on its own row, to make it easier to look through the list (especially in the `sunrise()` `sunset()` case), but that might just be me.

For me it would also make more sense to put the `check_docker()` and `update_docker()` under "Other functions", as they are not used (directly) for creating VP's.

And I might be missing something, but I don't really get the `'['(ppi)` etc subsetting functions, is that just not the normal subsetting? Seems a bit strange to include to me, and also looks a bit odd like that, but maybe that's normal.

I am actually thinking that the `sd_vvp_threshold()` and `rcs` should be in the "Create vertical profiles of birds", because they effect already the vp's (so before they get combined to vpts), right?

Great job you guys are doing arranging all of this! 🌟

**Comment by peterdesmet** [comment]
@plieper @CeciliaNilsson709 thanks for the feedback! 👏  I'll try to summarize in a todo list.

- [x] `is.pvolfile` vs `is.pvol`: see #134 
- [ ] `nexrad_to_odim()`: Only repeated function. @peterdesmet @plieper suggest to keep it in both "Reading radar data" & "Creating vertical profiles of birds" @adokter?
- [x] The fact that you get something when typing `pvol` is because a `summary(pvol)` function exists. You can write it either way, but since we list all public functions, it is included as such.
- [x] Description for `summary()` et al.: see #135
- [ ] @CeciliaNilsson709: yes, `sd_vvp_threshold()` and `rcs` check/update already created `vp`s 
 AND `vpts`. We could list them under "Reading vertical profile data" (for vp) AND "Combining vertical profiles into time series" (for vpts). For now I didn't want to repeat 4 functions, but we could. @adokter?

    Note: I wouldn't list them under "Creating vertical profiles of birds" as those functions are for already created vp/vpts (i.e. you can use them if you already have vp data). `calculate_vp` has parameters to set those when _creating_ vps.
- [ ] @adokter when initializing a docker container, do you call `update_docker` first? And then do `check_docker()`? Or the other way around?
- [ ] Where to put `update/check_docker()`: "Creating vertical profiles of birds" (@peterdesmet: only used for creating vps) or "Other functions" (@CeciliaNilsson709: not directly used for creating vps)
- [ ] @CeciliaNilsson709 I get that one row per function would make it easier to scan. The way the function documentation is setup now, is that very similar functions are linked together, so we only need to write one description for them. @adokter @stijnvanhoey I guess we want to keep it like that??
- [x] Subsetting: see #136

**Comment by CeciliaNilsson709** [comment]
> * [ ]  @CeciliaNilsson709: yes, `sd_vvp_threshold()` and `rcs` check/update already created `vp`s
>   AND `vpts`. We could list them under "Reading vertical profile data" (for vp) AND "Combining vertical profiles into time series" (for vpts). For now I didn't want to repeat 4 functions, but we could. @adokter?
>   Note: I wouldn't list them under "Creating vertical profiles of birds" as those functions are for already created vp/vpts (i.e. you can use them if you already have vp data). `calculate_vp` has parameters to set those when _creating_ vps.

This is confusing. Even if you can change it also for a vpts, it doesn't really have to do with combining vertical profiles into time series, right? It still (conceptually at least) changes the underlying vps that make up the time series. Maybe adding it to "Reading vertical profile data" and then include "changing" or something like that in the description for that group is better. You could also include it in the description of the function, eg: "set radar cross section for a object of class vp or vpts" (or maybe even "update radar cross section for a object of class vp or vpts" is better?)

**Comment by peterdesmet** [comment]
@CeciliaNilsson709 good point: let's include it under vp's only. 👍

**Comment by adokter** [comment]
Mm I actually apply `sd_vpp_threshold()` and `rcs()` more often to a vpts than to a vp, because often you use the same threshold and radar cross section for the full time series. So I do think it has to be clear that these functions are generic to any of the bioRad classes, i.e. `vp`, `vpts` and `vpi`

**Comment by CeciliaNilsson709** [comment]
Agree, but is it really more generic to list it only under vpts then? Another idea could be under "Other" with a clear description of the classes.

**Comment by adokter** [comment]
How about making a separate heading "Accessing profile metadata", this could list
* rcs
* rcs<-
* sd_vvp_threshold
* sd_vvp_threshold<-
* check_night: **note** this is also a generic function that acts on vp, vpts and vpi.

**Comment by peterdesmet** [comment]
New version with requested changes. Remarks:

- @plieper in #135 decided to have more or less similar description for `summary` etc., but more info on their page
- "Inspecting radar scans": title updated, description remained the same
- `check_docker` then `update_docker`
- #136 is not addressed yet.
- New section "Accessing **vertical** profile metadata", because we always refer to them as "vertical". Put at the end before other functions (after vp, vpts, vpi). Also includes `check_night`. 
-  "Creating vertical profiles **of biological targets**": I would add **of biological targets** to make the distinction clear between functions for just radar data (top) and those on biological data (below). @adokter let me know if you want another phrase, but I think we should explicit. "of birds" should probably be updated elsewhere in the package as well.

@adokter let me know if you have comments, and then I'll submit a pull request.

![function reference biorad 1](https://user-images.githubusercontent.com/600993/45740703-24e2ea80-bbf6-11e8-8db6-316589ae1fea.png)

**Comment by adokter** [comment]
@peterdesmet looking good!

**Comment by peterdesmet** [comment]
Included in `develop` branch via #142
