### ISSUE TITLE
vignettes not found

### ISSUE THREAD

**Issue by adokter** [adokter/bioRad#146]
This command used to work, but does not anymore:
```
vignette("functionality_overview")
```
I also get:
```
> vignette(package="bioRad")
no vignettes found
```

**Comment by peterdesmet** [comment]
It seems that devtools does not build vignettes by default when you `devtools::install_...()`. See "A note to devtools users" in [here](http://yihui.name/knitr/demo/vignette/). You need to explicitly do:

```r
devtools::install(build_vignettes = TRUE)
```

I tested this and it works then. Also tested this (without the above line of code) on other packages I installed via devtools and got the same problem. 

Since users are not aware of this, I hope that is not the case for a package installed from CRAN. In any case, I think it might be better to remove that comment from the README and point users to the website articles instead?

**Comment by adokter** [comment]
closed by commit 734c06a660be1d977aad0ffd8842df299a824c7f

**Comment by peterdesmet** [comment]
@adokter can you update your pkgdown to 1.1.0 and rebuild? That should get rid of some of the changes back and forth.

**Comment by adokter** [comment]
yes saw that, I've upgraded earlier somewhere this afternoon
