### ISSUE TITLE
NaN vs zero in integrate_to_ppi

### ISSUE THREAD

**Issue by BerendWijers** [adokter/bioRad#256]
The integrate_to_ppi produces NaN's whereas project_to_ppi produces NA's. NA's are omitted from the visualization when used in map(), NaN's are not. 
>Consider either checking for NA's and NaN's or let integrate_to_ppi produces NA's instead of NaN's.

**Comment by adokter** [comment]
Both functions should follow the same [conventions](https://github.com/adokter/bioRad/blob/e0ede427eb34007dc9985302d40cbdab158e0636/R/vp.R#L54-L63) as for vertical profiles, i.e.:
* `NA` Maps to 'nodata' in the ODIM convention: value to denote areas void of data (never radiated)
* `NaN` Maps to 'undetect' in the ODIM convention: denote areas below the measurement detection threshold (radiated but nothing detected). The value is also used when there are too few datapoints to calculate a quantity.
* `0` Maps to 0 in the ODIM convention: denote areas where the quantity has a measured value of zero (radiated and value zero detected or inferred).

Both NaN and NA are not plotted, the difference you see is because of introduced zeros I suspect. `project_as_ppi()` keeps the `NA` and `NaN` values of the scan object. `integrate_to_ppi()` generates 0's if all reflectivity scans at a certain pixel have NaN, i.e. if the airspace was empty in all scans.

I think you are suggesting that you want to change all values zero for vid and vir into NaN.

**Comment by BerendWijers** [comment]
My apologies for not replying sooner. 

You are absolutely correct - they are 0's. I agree with you and would not remove them as a base functionality as you "lose" information. 

It is very straightforward to remove the 0's yourself if you really want to.

Thanks for the information.
