### ISSUE TITLE
Give feedback on quantity/param

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#267]
When using a function, it would be nice param and quantity can be used interchangeably (or at least warned about).

I used:

    plot(ppi, quantity=“vid”)

Which plots vir (as that is the default param) without warning.

**Comment by adokter** [comment]
The distinction between `param` and `quantity` is:

* `param` is reserved for polar scan parameters, i.e. one of the products / scan moments in the raw data delivered by the radar.
* `quantity` is refers to the calculated quantities in a vertical profile, that are derived from the raw `param` data.
* `param` mirrors the polar scan parameter class `param` that stores the original products when loading a polar volume from file.

BUT: sometimes we want to convert `param` data into something else, for example a logarithmic reflectivity factor `DBZH` into a linear reflectivity `eta`, and we might want to store `eta` also as a scan moment in a pvol or scan object. This would break the convention of reserving `param` for the original products.

**Comment by peterdesmet** [comment]
Ok, so are you saying with your `eta` example that it is difficult to keep the distinction?

And in any case, it would be good if the user gets a warning.

**Comment by adokter** [comment]
> Ok, so are you saying with your `eta` example that it is difficult to keep the distinction?

Yes, the question is whether we want to call transformations of radar observables a `param` or a `quantity`, for example:
- you might want to plot a scan with `plot.scan()` on the linear `eta` scale instead of the default logarithmic `DBZH`. Something that people want to do quite regularly, because `eta` is actually proportional to bird density.
- or construction of other combined quantities, like the depolarization ratio for identification of biological targets, see [Kilambi et al.](  https://doi.org/10.1175/JTECH-D-17-0175.1), which is a combination of the RHOHV and ZDR `param` fields.

**Comment by adokter** [comment]
Checking for presence of `param` and `quantity` arguments in plot methods, and printing informative message when the wrong argument is used (59aa815b0cf8826ee5f30979bd48d222576bda3d). Also checking for scan parameter presence in `plot.scan` and `plot.ppi` (b998e980b8619df2f8e4f73675eadeb70126cc90)
