### ISSUE TITLE
Move as.data.frame to separate function page and deprecate parameter "quantities"

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#364]
Currently this function is listed on vp.R and vpts.R, with duplicate documentation.

- [x] Move to separate page
- [x] Join documentation
- [x] Markdown documentation
- [x] Deprecated `quantities`

**Comment by peterdesmet** [comment]
Tackle this after or with #356

**Comment by peterdesmet** [comment]
I've started with this on https://github.com/adokter/bioRad/tree/as.data.frame, but it is unclear to how I should bundle `as.data.frame.vp` and `as.data.frame.vpts` in one page without creating a:

```R
as.data.frame <- function(x, row.names = NULL, optional = FALSE,
                          quantities = names(x$data), suntime = TRUE,
                          geo = TRUE, elev = -0.268, lat = NULL,
                          lon = NULL, ...) {
  UseMethod("as.data.frame", x)
}
```

(similar to `rcs()`) which then masks `as.data.frame` from `base` on bioRad install. @adokter any suggestions?

**Comment by adokter** [comment]
Indeed I believe you should only define the S3 method, because `as.data.frame` method dispatch is already defined in base R.

But you can document both in the same same page, for example by adding `@rdname as.data.frame.vp` in the roxygen header of `as.data.frame.vpts()`, and only document `as.data.frame.vp()`.

This is an example of a S3 as.data.frame method of a different ropensci package:

https://github.com/ropensci/git2r/blob/1206ea384132f6e1503da1667f129e1bbf90c0e6/R/repository.R#L17-L81

**Comment by peterdesmet** [comment]
Ok, great! Will try to adapt.
