### ISSUE TITLE
Stick to one naming convention

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#51]
While listing the functions in #50, I noticed there are a lot of name conventions used (`lowerCamelCase`, `period.separated `, `underscore_separated `) for those functions. Not sure if we want to tackle this now (but better now than later), but the it would be good [to stick to 1](https://www.r-bloggers.com/consistent-naming-conventions-in-r/). 😄  The link suggests `underscore_separated`.

**Comment by adokter** [comment]
@peterdesmet fully agree with that

**Comment by peterdesmet** [comment]
Any preference? Mine is underscore. I guess this will break scripts using bioRad functions (once people update the package)?

**Comment by adokter** [comment]
Yes I also prefer underscore, and reserve the dot for method dispatching only.

Most of the dots are indeed method functions, except for the `is.XXX`, `read.XXX` and `as.data.frame.vpts` functions. I did that because of convention in the R language (e.g. there are many `as.data.frame` class functions, so R hasn't really stuck to reserving the dot for method dispatch itself).

Hesitant to change functions in the namespace indeed, as it will break things. Functions outside namespace can be changed. 

We could do a push at some point to also change namespace functions, but I prefer to wait until there is a clearer list on what should be changed structure-wise

**Comment by adokter** [comment]
Check use of `quantity` and `param`.

`quantity` and `param` are both used as function arguments. `param` is also one of the object classes

`param` as a function argument is used to refer to radar observables only (dbz, vrad, etc), i.e. those that can be contained in the `param` class.

Quantity can refer to more profile quantities (like height of the altitude layer), and is thus more generic.

`plot.ppi` has param as function argument
`plot.vp` has quantity as function argument
which is not very intuitive

It seems more consistent to restrict `param` only to the class object, and have all function arguments be 'quantity'

**Comment by adokter** [comment]
https://journal.r-project.org/archive/2012-2/RJournal_2012-2_Baaaath.pdf

**Comment by adokter** [comment]
We can rename functions while keeping the old name working as well, as follows (using roxygen):
```
#' @name oldName-deprecated
#' @rdname bioRad-deprecated
#' @section \code{oldName}:
#' For \code{oldName}, use \code{\link{newName}}.
#' @export
oldName=function(arg1, arg2){
  .Deprecated("newName")
  newName(arg1, arg2)
}
```
This will generate a `bioRad-deprecated` help page listing all the deprecated functions, and give users a warning to switch to the new name

**Comment by adokter** [comment]
old name | new name | comments
--- | --- | ---
as.data.frame.vpts | tbd |
basemap | tbd |
beamheight | tbd |
beamwidth | tbd |
bind | tbd |
c.vp | tbd |
checkDocker | tbd |
cmt | tbd |
composite | tbd |
day | tbd |
dbz2eta | tbd |
dim.ppi | tbd |
dim.scan | tbd |
download_vp | tbd |
elangle | tbd |
eta2dbz | tbd |
fetch | tbd |
getscan | tbd |
h5ODIMobject | tbd |
is.param | tbd |
is.ppi | tbd |
is.pvol | tbd |
is.pvolfile | tbd |
is.scan | tbd |
is.vp | tbd |
is.vpfile | tbd |
is.vplist | tbd |
is.vpts | tbd |
map | tbd |
match_filenames | tbd |
mt | tbd |
mtr | tbd |
night | tbd |
plot.ppi | tbd |
plot.vivp | tbd |
plot.vp | tbd |
plot.vpts | tbd |
ppi | tbd |
rcs | tbd |
rcs<- | tbd |
read.pvol | tbd |
readvp | tbd |
readvp.list | tbd |
readvp.table | tbd |
regularize | tbd |
retrieve_vp_paths | tbd |
rsl2odim | tbd |
sd_vvp | tbd |
sd_vvp<- | tbd |
suntime | tbd |
updateDocker | tbd |
url_existence | tbd |
vintegrate | tbd |
vol2bird | tbd |
vpts | tbd |

**Comment by adokter** [comment]
@peterdesmet @stijnvanhoey what do you think of the names above? I'm still a bit undecided on the "br_" prefix, but such a convention is handy with auto-completion in RStudio. Please improve where you can!

**Comment by adokter** [comment]
@plieper @CeciliaNilsson709 if you want to chime in on bioRad's function namings as well, please do

**Comment by peterdesmet** [comment]
Good that deprecated names can be listed. Will have a look at suggested names. If we go for a prefix, we might as well go for the more recognizable and not that much longer biorad_, no? But not sure a prefix is necesssary, @stijnvanhoey?

**Comment by adokter** [comment]
We also have to decide on a coherent naming convention of the function arguments, which may in fact be a bigger task than the naming of the functions

**Comment by peterdesmet** [comment]
@adokter, I finished my review of the function names and ran them by @stijnvanhoey. See [this spreadsheet](https://docs.google.com/spreadsheets/d/1EhdHaHTF3paiU3PlNUkxPhUz_DgwVXdW8fcDaZn7XyM/edit?usp=sharing) for the proposal.

General thoughts in naming functions:

1. Stick to S3 convention and have polymorphistic functions (like `plot`) that work for multiple objects
1. Don't use `br_` or `biorad_` prefix
1. Where logical, name functions so these can be grouped: `docker_check` & `docker_update` (not `check_docker` & `update_docker`). Helps in alphabetical listing or tab completion
1. Convert functions use `_to_`: `dbz_to_eta` (not `dbz2eta`), `pvolfile_to_vp` (not `vol2bird`)
1. Objects can be created with a function bearing their name:
    - `ppi(scan)` => `ppi`
    - `vpts(c(vp, vp))` => `vpts`
    - `scan(pvol, angle = 2) => `scan` (not `getscan`)
    - `vpi(vpts)` => `vpi` (not `integrate_heights`)
    - `vp(vpfile)` => `vp` (not `read.vp`). Also supports reading a vector of vp files
1. Keep what I assume are _known_  abbreviations, like `mtr`, `rtr`, `rcs`, `rvsd` (not `sd_vvd`)
1. Functions specific to a single object (and no planned support for other objects) start with that object name: `ppi_composite`, `vpfile_download`, `vpts_from_text` (not `readvp.table`), `vpts_regularize`. There aren't that many, but helps in alphabetical listing or tab completion

Let me know what you think. If easier, we could arrange another call too.

**Comment by adokter** [comment]
@peterdesmet thanks looks good, here some thoughts (I can't edit the excel file, so all comments here, following the order of the excel)
* `pvolfile` listed as an object, but this is only a string with the path to a file. So `dim.pvolfile` not needed
* `is.quantity` I think you mean here `is.param`; ok to hide from user for now, but prefer to keep under the hood. I expect we later want functionality to merge separate `param` into `scan`, as certain countries provide separate files for separate param (sigh...)
* This means we want also a `param(pvol, angle = 2, param = "DBZH")` and `param(scan, param = "DBZH")`function
* `is.rslfile`: Prefer a `is.pvolfile` that works for both european and US data, so have the user not worry about formats. RSL reads already many radar formats, see https://trmm-fc.gsfc.nasa.gov/trmm_gv/software/rsl/, so not really itself a radar data type
* `mt`, `mt_cumul`, `mtr`, `rtr`: these are now columns in the `vpi` object (which itself is a specially classed `data.frame`). Because all these values are conditional on the definition of the transect orientation (parameter `alpha` in `vintegrate`/`vpi`), `alpha` should be stored as an attribute to `vpi`
* deprecate `cmt`/`mt_cumul`; the `vpi` dataframe already will have a column `mt` which gives the (cumulative) migration traffic.
* `night`: currently does something different than `day(object)`: day tests on bioRad objects, while `night(lon, lat, date)` checks whether it is night on a given location and date. Name is confusing, we could call it `night_at_location` instead?
*  `pvolfile_to_vp()`/`pvol_to_vp()`: for technical reasons we can currently only go from a pvolfile to a vp, in the future likely from a pvol to a vp as well. I prefer `pvol_to_vp()` as it is shorter (pvolfile hard to pronounce), and we could have this function accept both a pvolfile and (in the future) a pvol. Currently the function can also output a vpfile, so the `_to_vp` is already ambiguous, so a little more pvol/pvolfile ambiguity doesn't matter :)
*

**Comment by peterdesmet** [comment]
Odd, you should have access with your gmail account. But in response:

1. OK, marked as `deprecate: don't add`
2. Correct, updated `quantity` back to `param` were appropriate. Marked as `hide`
3. Indeed, function added to spreadsheet (twice, for `pvol` and `scan` object). I'd argue to use the function parameter `quantity = ...` everywhere, not `param`
4. Ok, all reference to `rslfile` object removed
5. Ok, do I need to add/update something for that?
6. Ok, marked as deprecate. I noticed `mt` is proposed for deprecation as well (#76) so marked as such
7. Ooooooh! 😮Both both do return TRUE/FALSE. In that case... and assuming people are generally more interested in nights, why don't we call `day()` -> `night()` and have that function work on bioRad objects AND locations? Pinging @stijnvanhoey for advice
8. Great! I prefer `pvol_to_vp` as well! Updated. Currently that function does (too) much... it would be nicer there was just `pvol()` to read, `pvol_to_vp()` to transform, and `vpfile()` to write it back to a file, but I understand why it was designed that way.

**Comment by peterdesmet** [comment]
Haha! Ok, to continue the list:

9. Is that function often used? Would it make sense to have `object_type`/`biorad_object_type`, that returns `vp`, `scan`, `pvol`?
10. OK
11. OK, marked for deprecation.

I haven't checked where in bioRad lists are used and where vectors. E.g. for `vpfile_select` it makes sense to get a vector back `c(vpfile, vpfile, vpfile)` that can be passed on to `vp()` to get `c(vp, vp, vp)` that can be passed to `vpts()`

**Comment by stijnvanhoey** [comment]
7. +1 on the `night()` function being able to do either biorad object or custom location; deprecate `day()`

**Comment by adokter** [comment]
9. not used a lot. Has come in handy so people can check what kind of a file they got from meteorologists. More useful when we can combine scans into pvols.

**Comment by peterdesmet** [comment]
9. Ok, if you think it will be useful later, we can keep (lowercase) `odim_object_type` around.

For the suggested functions `object_type` (returning `pvol`, `vp`, ...), `pvolfile_type` (returning `NEXRAD`, `ODIM`) and more functionality for `pvol_to_vp`, I'll let you issues if need be.

Let me know if you consider the renaming approved.

**Comment by adokter** [comment]
* added issue #83 for `pvolfile_type`.
* don't think we need `object_type`, already handled by `class`.
* more functionality `pvol_to_vp` / splitting out file I/O: leaving that for now. Would likely require getting rid of Docker entirely, which would be nice, but will be a complicated
* Renaming function names approved!

Still to do: renaming all the function arguments; we at least need to settle on some convention.

Do you and Stijn have time to spend on the refactor as well? I would like to deprecate without breaking things, see this [earlier comment](https://github.com/adokter/bioRad/issues/51#issuecomment-374747768), so it will be quite a bit of work ...

**Comment by adokter** [comment]
Issue #20 needs to be resolved as part of this issue as well

**Comment by adokter** [comment]
naming of `sd_vvp`: there is the `sd_vvp` profile quantity, and there is the threshold that is applied to this quantity. `sd_vvp()` sets/retrieves this threshold to which `sd_vvp` quantity is compared

In the ODIM hdf5 profile file (see https://github.com/adokter/vol2bird/wiki/ODIM-bird-profile-format-specification) we use `sd_vvp` for the quantity and `sd_vvp_thresh` for the threshold.

I'm wondering whether for consistency it would be better to keep `sd_vvp()` or `sd_vvp_thresh()` instead of introducing the new `rvsd()`. Of course I can change sd_vvp to rsvd in the [vol2bird](https://github.com/adokter/vol2bird/) code, but then we have different versions floating around, which I think is not worth it.

**Comment by peterdesmet** [comment]
@adokter

- Yay! Approved!
- For the function arguments I would start a new issue
- sd_vvp(): either we use the more consistent (with other functions) name rvsd() and nicely deprecate sd_vvp(), or we keep sd_vvp(). Your choice. 😌

**Comment by peterdesmet** [comment]
Closing this discussion issue: todo list is part of #84.
